export default {
    GET_POKEMONS_REQUEST: '@pokemon/GET_POKEMONS_REQUEST',
    GET_POKEMONS_PAGINATION: '@pokemon/GET_POKEMONS_PAGINATION',
    GET_POKEMON_REQUEST: '@pokemon/GET_POKEMON_REQUEST',
    GET_POKEMON_FAILURE: '@pokemon/GET_POKEMON_FAILURE',
};
